package com.ma.rest.mapper.dao;

import com.ma.rest.pojo.Comment;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_comment
     *
     * @mbggenerated
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_comment
     *
     * @mbggenerated
     */
    int insertSelective(Comment record);
}