package com.ma.rest.mapper.dao;

import com.ma.rest.base.model.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_order
     *取消订单
     * @mbggenerated
     */
    int deleteByKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_order
     *
     * @mbggenerated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_order
     *生成订单
     * @mbggenerated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_order
     *
     * @mbggenerated
     */
    Order selectByKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Order record);

    /**
     * 查询用户的订单列表
     * @return
     */
    List<Order> selectOrderList(@Param("userId") Integer userId, @Param("start") Integer start, @Param("rows") Integer rows,@Param("status") String status);
    /**
     * 查询商户消费列表
     * @return
     */
    List<Order> selectSellerOrderList(@Param("sellerUid") Integer sellerUid, @Param("start") Integer start, @Param("rows") Integer rows,@Param("status") String status,@Param("beginTime") String beginTime,@Param("endTime") String endTime);

    /**
     * 订单详情
     */
    /**
     * 总条数
     * @return
     */
    Integer queryAllRows(@Param("userId") Integer userId,@Param("status") String status);
    Integer deleteBatch(@Param("orderIds") String orderIds);
    Order selectByOrderNumber(@Param("orderNumber") String orderNumber);
    Order selectOrderDetailById(@Param("userId")Integer userId,@Param("orderId") Integer orderId);
}