package com.ma.rest.mapper.dao;


import com.ma.rest.base.model.RelOderGoods;

public interface RelOderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_goods
     *
     * @mbggenerated
     */
    int deleteByPrimary(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_goods
     *
     * @mbggenerated
     */
    int insert(RelOderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_goods
     *
     * @mbggenerated
     */
    int insertSelective(RelOderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_goods
     *
     * @mbggenerated
     */
    RelOderGoods selectByPrimary(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelOderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_order_goods
     *
     * @mbggenerated
     */
    int updateByPrimary(RelOderGoods record);
}