package com.ma.rest.mapper.dao;

import com.ma.rest.pojo.Reply;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_reply
     *
     * @mbggenerated
     */
    int insert(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_reply
     *
     * @mbggenerated
     */
    int insertSelective(Reply record);

    /**
     * 通过评论的id去获取所有的回复
     * @param cid
     * @return
     */
    List<Reply> queryReplyByCid(@Param("id") Integer cid);


}