package com.ma.rest.mapper.dao;


import com.ma.rest.base.model.Serial;

public interface SerialMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_serial
     *
     * @mbggenerated
     */
    int deleteBySerialId(Integer serialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_serial
     *
     * @mbggenerated
     */
    int insert(Serial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_serial
     *
     * @mbggenerated
     */
    int insertSelective(Serial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_serial
     *
     * @mbggenerated
     */
    Serial selectBySerialId(Integer serialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_serial
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Serial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_serial
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Serial record);
    int truncateTable();
    Serial selectSerial();
}