package com.ma.rest.base.model;

import java.io.Serializable;
import java.util.List;

public class AfterSale implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_aftersale.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_aftersale.meet_question
     *
     * @mbggenerated
     */
    private String meetQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_aftersale.describe_question
     *
     * @mbggenerated
     */
    private String describeQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_aftersale.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_aftersale.picture_url
     *
     * @mbggenerated
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ma_aftersale
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ma_aftersale.id
     *
     * @return the value of ma_aftersale.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ma_aftersale.id
     *
     * @param id the value for ma_aftersale.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ma_aftersale.meet_question
     *
     * @return the value of ma_aftersale.meet_question
     *
     * @mbggenerated
     */
    public String getMeetQuestion() {
        return meetQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ma_aftersale.meet_question
     *
     * @param meetQuestion the value for ma_aftersale.meet_question
     *
     * @mbggenerated
     */
    public void setMeetQuestion(String meetQuestion) {
        this.meetQuestion = meetQuestion == null ? null : meetQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ma_aftersale.describe_question
     *
     * @return the value of ma_aftersale.describe_question
     *
     * @mbggenerated
     */
    public String getDescribeQuestion() {
        return describeQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ma_aftersale.describe_question
     *
     * @param describeQuestion the value for ma_aftersale.describe_question
     *
     * @mbggenerated
     */
    public void setDescribeQuestion(String describeQuestion) {
        this.describeQuestion = describeQuestion == null ? null : describeQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ma_aftersale.order_id
     *
     * @return the value of ma_aftersale.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ma_aftersale.order_id
     *
     * @param orderId the value for ma_aftersale.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ma_aftersale.picture_url
     *
     * @return the value of ma_aftersale.picture_url
     *
     * @mbggenerated
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ma_aftersale.picture_url
     *
     * @param pictureUrl the value for ma_aftersale.picture_url
     *
     * @mbggenerated
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_aftersale
     *
     * @mbggenerated
     */
    private List<String> aftersaleImgArr;

    public List<String> getAftersaleImgArr() {
        return aftersaleImgArr;
    }

    public void setAftersaleImgArr(List<String> aftersaleImgArr) {
        this.aftersaleImgArr = aftersaleImgArr;
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AfterSale other = (AfterSale) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMeetQuestion() == null ? other.getMeetQuestion() == null : this.getMeetQuestion().equals(other.getMeetQuestion()))
            && (this.getDescribeQuestion() == null ? other.getDescribeQuestion() == null : this.getDescribeQuestion().equals(other.getDescribeQuestion()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getPictureUrl() == null ? other.getPictureUrl() == null : this.getPictureUrl().equals(other.getPictureUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_aftersale
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMeetQuestion() == null) ? 0 : getMeetQuestion().hashCode());
        result = prime * result + ((getDescribeQuestion() == null) ? 0 : getDescribeQuestion().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getPictureUrl() == null) ? 0 : getPictureUrl().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_aftersale
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", meetQuestion=").append(meetQuestion);
        sb.append(", describeQuestion=").append(describeQuestion);
        sb.append(", orderId=").append(orderId);
        sb.append(", pictureUrl=").append(pictureUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}