package com.ma.rest.base.model;

import java.io.Serializable;

public class Serial implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_serial.serial_id
     *
     * @mbggenerated
     */
    private Integer serialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_serial.serial_number
     *
     * @mbggenerated
     */
    private Integer serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ma_serial
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ma_serial.serial_id
     *
     * @return the value of ma_serial.serial_id
     *
     * @mbggenerated
     */
    public Integer getSerialId() {
        return serialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ma_serial.serial_id
     *
     * @param serialId the value for ma_serial.serial_id
     *
     * @mbggenerated
     */
    public void setSerialId(Integer serialId) {
        this.serialId = serialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ma_serial.serial_number
     *
     * @return the value of ma_serial.serial_number
     *
     * @mbggenerated
     */
    public Integer getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ma_serial.serial_number
     *
     * @param serialNumber the value for ma_serial.serial_number
     *
     * @mbggenerated
     */
    public void setSerialNumber(Integer serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_serial
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Serial other = (Serial) that;
        return (this.getSerialId() == null ? other.getSerialId() == null : this.getSerialId().equals(other.getSerialId()))
            && (this.getSerialNumber() == null ? other.getSerialNumber() == null : this.getSerialNumber().equals(other.getSerialNumber()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_serial
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSerialId() == null) ? 0 : getSerialId().hashCode());
        result = prime * result + ((getSerialNumber() == null) ? 0 : getSerialNumber().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_serial
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", serialId=").append(serialId);
        sb.append(", serialNumber=").append(serialNumber);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}