package com.ma.rest.pojo;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Comment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_comment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_comment.topic_id
     *
     * @mbggenerated
     */
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_comment.topic_type
     *
     * @mbggenerated
     */
    private String topicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_comment.contnet
     *
     * @mbggenerated
     */
    private String contnet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_comment.from_uid
     *
     * @mbggenerated
     */
    private Integer fromUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_comment.comment_time
     *
     * @mbggenerated
     */
    private Date commentTime;
    private List<Reply> replies;

    public List<Reply> getReplies() {
        return replies;
    }

    public void setReplies(List<Reply> replies) {
        this.replies = replies;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ma_comment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ma_comment.id
     *
     * @return the value of ma_comment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ma_comment.id
     *
     * @param id the value for ma_comment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ma_comment.topic_id
     *
     * @return the value of ma_comment.topic_id
     *
     * @mbggenerated
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ma_comment.topic_id
     *
     * @param topicId the value for ma_comment.topic_id
     *
     * @mbggenerated
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ma_comment.topic_type
     *
     * @return the value of ma_comment.topic_type
     *
     * @mbggenerated
     */
    public String getTopicType() {
        return topicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ma_comment.topic_type
     *
     * @param topicType the value for ma_comment.topic_type
     *
     * @mbggenerated
     */
    public void setTopicType(String topicType) {
        this.topicType = topicType == null ? null : topicType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ma_comment.contnet
     *
     * @return the value of ma_comment.contnet
     *
     * @mbggenerated
     */
    public String getContnet() {
        return contnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ma_comment.contnet
     *
     * @param contnet the value for ma_comment.contnet
     *
     * @mbggenerated
     */
    public void setContnet(String contnet) {
        this.contnet = contnet == null ? null : contnet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ma_comment.from_uid
     *
     * @return the value of ma_comment.from_uid
     *
     * @mbggenerated
     */
    public Integer getFromUid() {
        return fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ma_comment.from_uid
     *
     * @param fromUid the value for ma_comment.from_uid
     *
     * @mbggenerated
     */
    public void setFromUid(Integer fromUid) {
        this.fromUid = fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ma_comment.comment_time
     *
     * @return the value of ma_comment.comment_time
     *
     * @mbggenerated
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ma_comment.comment_time
     *
     * @param commentTime the value for ma_comment.comment_time
     *
     * @mbggenerated
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_comment
     *
     * @mbggenerated
     */
    private String commentPic;

    public String getCommentPic() {
        return commentPic;
    }

    public void setCommentPic(String commentPic) {
        this.commentPic = commentPic;
    }
    private List<String> commentPicAttr;

    public List<String> getCommentPicAttr() {
        return commentPicAttr;
    }

    public void setCommentPicAttr(List<String> commentPicAttr) {
        this.commentPicAttr = commentPicAttr;
    }
    //一对一对应商户
    private MaUserInfo maUserInfo;

    public MaUserInfo getMaUserInfo() {
        return maUserInfo;
    }

    public void setMaUserInfo(MaUserInfo maUserInfo) {
        this.maUserInfo = maUserInfo;
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Comment other = (Comment) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTopicId() == null ? other.getTopicId() == null : this.getTopicId().equals(other.getTopicId()))
            && (this.getTopicType() == null ? other.getTopicType() == null : this.getTopicType().equals(other.getTopicType()))
            && (this.getContnet() == null ? other.getContnet() == null : this.getContnet().equals(other.getContnet()))
            && (this.getFromUid() == null ? other.getFromUid() == null : this.getFromUid().equals(other.getFromUid()))
            && (this.getCommentTime() == null ? other.getCommentTime() == null : this.getCommentTime().equals(other.getCommentTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_comment
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTopicId() == null) ? 0 : getTopicId().hashCode());
        result = prime * result + ((getTopicType() == null) ? 0 : getTopicType().hashCode());
        result = prime * result + ((getContnet() == null) ? 0 : getContnet().hashCode());
        result = prime * result + ((getFromUid() == null) ? 0 : getFromUid().hashCode());
        result = prime * result + ((getCommentTime() == null) ? 0 : getCommentTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma_comment
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", topicId=").append(topicId);
        sb.append(", topicType=").append(topicType);
        sb.append(", contnet=").append(contnet);
        sb.append(", fromUid=").append(fromUid);
        sb.append(", commentTime=").append(commentTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}