package com.ma.rest.pojo;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
public class Reply implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.comment_id
     *
     * @mbggenerated
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.reply_id
     *
     * @mbggenerated
     */
    private Integer replyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.reply_type
     *
     * @mbggenerated
     */
    private String replyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.from_uid
     *
     * @mbggenerated
     */
    private Integer fromUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.to_uid
     *
     * @mbggenerated
     */
    private Integer toUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.reply_time
     *
     * @mbggenerated
     */
    private Date replyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ma_reply
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    private Integer goodsStar;

    private Integer serviceStar;

    private Integer matchStar;

    private String commentImg;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCommentId() {
        return commentId;
    }

    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    public Integer getReplyId() {
        return replyId;
    }

    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    public String getReplyType() {
        return replyType;
    }

    public void setReplyType(String replyType) {
        this.replyType = replyType;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getFromUid() {
        return fromUid;
    }

    public void setFromUid(Integer fromUid) {
        this.fromUid = fromUid;
    }

    public Integer getToUid() {
        return toUid;
    }

    public void setToUid(Integer toUid) {
        this.toUid = toUid;
    }

    public Date getReplyTime() {
        return replyTime;
    }

    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Integer getGoodsStar() {
        return goodsStar;
    }

    public void setGoodsStar(Integer goodsStar) {
        this.goodsStar = goodsStar;
    }

    public Integer getServiceStar() {
        return serviceStar;
    }

    public void setServiceStar(Integer serviceStar) {
        this.serviceStar = serviceStar;
    }

    public Integer getMatchStar() {
        return matchStar;
    }

    public void setMatchStar(Integer matchStar) {
        this.matchStar = matchStar;
    }

    public String getCommentImg() {
        return commentImg;
    }

    public void setCommentImg(String commentImg) {
        this.commentImg = commentImg;
    }
}