package com.ma.rest.pojo;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
public class Reply implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.comment_id
     *
     * @mbggenerated
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.reply_id
     *
     * @mbggenerated
     */
    private Integer replyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.reply_type
     *
     * @mbggenerated
     */
    private String replyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.from_uid
     *
     * @mbggenerated
     */
    private Integer fromUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.to_uid
     *
     * @mbggenerated
     */
    private Integer toUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma_reply.reply_time
     *
     * @mbggenerated
     */
    private Date replyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ma_reply
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    private Integer goodsStar;

    private Integer serviceStar;

    private Integer matchStar;

    private String commentImg;
}